version: "3.9"

services:
    api:
        build:
            context: .
            dockerfile: ./docker/local/django/Dockerfile
        command: /start
        container_name: django-api
        volumes:
            - .:/app
            - ./staticfiles:/app/staticfiles
            - ./mediafiles:/app/mediafiles
        ports:
            - "8000:8000"
        env_file:
            - ./.envs/.local/.django
            - ./.envs/.local/.postgres
        depends_on:
            - postgres
            - mailhog
        networks:
            - APP

    postgres:
        build:
            context: .
            dockerfile: ./docker/local/postgres/Dockerfile
        container_name: postgres
        volumes:
            - local_postgres_data:/var/lib/postgresql/data
            - local_postgres_data_backups:/backups
        env_file:
            - ./.envs/.local/.postgres
        networks:
            - APP

    mailhog:
        image: mailhog/mailhog:v1.0.0
        container_name: mailhog
        ports:
            - "8025:8025"
        networks:
            - APP



networks:
    APP:
        driver: bridge

volumes:
    local_postgres_data: {}
    local_postgres_data_backups: {}
    static_volume:
    media_volume:
