# Generated by Django 4.1.5 on 2023-01-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="about_me",
        ),
        migrations.AddField(
            model_name="profile",
            name="job_role",
            field=models.CharField(default="-", max_length=60, verbose_name="job role"),
            preserve_default=False,
        ),
    ]
